import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { test } from "node:test";

const file = (path) => new URL(`../${path}`, import.meta.url);
const read = (path) => readFileSync(file(path), "utf8");

test("the product offers only Free and Plus", () => {
  const runtimeFiles = [
    "src/lib/plans.ts",
    "src/lib/planIntent.ts",
    "src/lib/server/razorpay.ts",
    "src/app/api/payments/create-subscription/route.ts",
    "src/components/velora/pricing-data.ts",
    "src/components/velora/PricingPageContent.tsx",
    "src/components/settings/PlanSettings.tsx",
    "src/components/settings/settings-types.ts",
    "src/components/VaultApp.tsx",
    "src/app/pricing/page.tsx",
  ];
  const combined = runtimeFiles.map(read).join("\n");

  assert.doesNotMatch(combined, /family/i);
  assert.match(read("src/lib/plans.ts"), /export type PlanId = "free" \| "plus"/);
  const pricing = read("src/components/velora/pricing-data.ts");
  const tiers = pricing.slice(pricing.indexOf("export const PRICING_TIERS"), pricing.indexOf("type ComparisonValue"));
  assert.equal((tiers.match(/id:\s*"(?:free|plus)"/g) ?? []).length, 2);
});

test("legacy Family records are safely migrated to Plus", () => {
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_remove_family_plan.sql"))?.name;
  assert.ok(migrationName, "remove_family_plan migration must be generated by the Supabase CLI");
  const migrationPath = `supabase/migrations/${migrationName}`;
  assert.equal(existsSync(file(migrationPath)), true);
  const migration = read(migrationPath);

  assert.match(migration, /update\s+public\.app_members[\s\S]*set\s+plan\s*=\s*'plus'[\s\S]*where\s+plan\s*=\s*'family'/i);
  assert.match(migration, /update\s+public\.subscriptions[\s\S]*set\s+plan\s*=\s*'plus'[\s\S]*where\s+plan\s*=\s*'family'/i);
  assert.match(migration, /check\s*\(plan\s+in\s*\('free',\s*'plus'\)\)/i);
  assert.match(migration, /check\s*\(plan\s*=\s*'plus'\)/i);
});

test("subscription cancellation is scheduled for the billing-period end", () => {
  const razorpay = read("src/lib/server/razorpay.ts");
  const route = read("src/app/api/payments/cancel/route.ts");
  const settings = read("src/components/settings/PlanSettings.tsx");

  assert.match(razorpay, /JSON\.stringify\(\{\s*cancel_at_cycle_end:\s*true\s*\}\)/);
  assert.match(route, /cancel_at_cycle_end:\s*true/);
  assert.match(route, /const \{ error: updateError \}/);
  assert.match(route, /if \(updateError\) throw updateError/);
  assert.doesNotMatch(route, /status:\s*"cancelled"/);
  assert.match(settings, /Cancellation scheduled/);
  assert.match(settings, /cancel_at_cycle_end/);
});

test("Razorpay webhook idempotency uses the provider event header", () => {
  const route = read("src/app/api/payments/webhook/route.ts");

  assert.match(route, /headers\.get\("x-razorpay-event-id"\)/);
  assert.match(route, /createHash\("sha256"\)\.update\(rawBody\)/);
  assert.doesNotMatch(route, /typeof record\.id === "string"/);
});

test("all terminal and authorization subscription states are handled", () => {
  const route = read("src/app/api/payments/webhook/route.ts");
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_razorpay_live_hardening.sql"))?.name;
  assert.ok(migrationName, "Razorpay live hardening migration must exist");
  const migration = read(`supabase/migrations/${migrationName}`);

  assert.match(route, /case "subscription\.authenticated"/);
  assert.match(route, /case "subscription\.expired"/);
  assert.match(migration, /'expired'/);
});

test("unfinished checkout is reused and concurrent orphan subscriptions are cleaned up", () => {
  const razorpay = read("src/lib/server/razorpay.ts");
  const route = read("src/app/api/payments/create-subscription/route.ts");
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_razorpay_live_hardening.sql"))?.name;
  assert.ok(migrationName, "Razorpay live hardening migration must exist");
  const migration = read(`supabase/migrations/${migrationName}`);

  assert.match(razorpay, /fetchSubscription/);
  assert.match(razorpay, /cancelSubscriptionImmediately/);
  assert.match(route, /existing\?\.status === "created"/);
  assert.match(route, /cancelSubscriptionImmediately\(subscription\.id\)/);
  assert.match(migration, /create unique index[\s\S]*subscriptions_one_open_per_user/i);
});

test("subscription duration stays within Razorpay's 100-year maximum", () => {
  const razorpay = read("src/lib/server/razorpay.ts");
  const route = read("src/app/api/payments/create-subscription/route.ts");

  assert.match(razorpay, /totalCount:\s*number/);
  assert.match(razorpay, /total_count:\s*params\.totalCount/);
  assert.match(razorpay, /customer_notify:\s*true/);
  assert.match(route, /period === "monthly" \? 120 : 100/);
});

test("out-of-order webhook deliveries cannot overwrite newer subscription state", () => {
  const route = read("src/app/api/payments/webhook/route.ts");
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_razorpay_event_ordering.sql"))?.name;
  assert.ok(migrationName, "Razorpay event ordering migration must exist");
  const migration = read(`supabase/migrations/${migrationName}`);

  assert.match(migration, /last_razorpay_event_at/);
  assert.match(route, /eventTimestamp/);
  assert.match(route, /last_razorpay_event_at\.is\.null,last_razorpay_event_at\.lte\./);
  assert.match(route, /\.select\("user_id,plan"\)/);
});

test("scheduled billing changes reconcile from the subscription updated webhook", () => {
  const route = read("src/app/api/payments/webhook/route.ts");

  assert.match(route, /case "subscription\.updated"/);
  assert.match(route, /applySubscriptionState\(admin, sub\.id, sub\.status \|\| "active", occurredAt, "preserve", sub\.current_end, sub\.plan_id\)/);
});

test("a stale billing reconciliation retry cannot stomp a subscription a newer webhook event already fixed", () => {
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_billing_reconciliation_freshness_guard.sql"))?.name;
  assert.ok(migrationName, "billing_reconciliation_freshness_guard migration must exist");
  const migration = read(`supabase/migrations/${migrationName}`);

  // The corrective write must be scoped to rows that haven't received a
  // newer Razorpay event since the issue was queued - the same freshness
  // guard the webhook itself uses - so a stale retry can't overwrite state a
  // later, more-authoritative event already applied correctly.
  assert.match(migration, /where public\.subscriptions\.razorpay_subscription_id = v_issue\.razorpay_subscription_id[\s\S]{0,80}and \(/);
  assert.match(migration, /public\.subscriptions\.last_razorpay_event_at is null[\s\S]{0,20}or public\.subscriptions\.last_razorpay_event_at <= v_issue\.created_at/);

  // "Subscription row doesn't exist at all" must be checked independently of
  // the freshness guard, so a merely-stale-but-existing row is never
  // reported as SUBSCRIPTION_NOT_FOUND.
  assert.match(migration, /select exists \(\s*select 1 from public\.subscriptions/);
  assert.match(migration, /if not v_subscription_exists then\s*raise exception 'SUBSCRIPTION_NOT_FOUND' using errcode = 'P0003'/);
});
