import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { test } from "node:test";

const file = (path) => new URL(`../${path}`, import.meta.url);
const read = (path) => readFileSync(file(path), "utf8");

test("the product offers only Free and Plus", () => {
  const runtimeFiles = [
    "src/lib/plans.ts",
    "src/lib/planIntent.ts",
    "src/lib/server/razorpay.ts",
    "src/app/api/payments/create-subscription/route.ts",
    "src/components/dreelio/pricing-data.ts",
    "src/components/dreelio/PricingPageContent.tsx",
    "src/components/settings/PlanSettings.tsx",
    "src/components/settings/settings-types.ts",
    "src/components/VaultApp.tsx",
    "src/app/pricing/page.tsx",
  ];
  const combined = runtimeFiles.map(read).join("\n");

  assert.doesNotMatch(combined, /family/i);
  assert.match(read("src/lib/plans.ts"), /export type PlanId = "free" \| "plus"/);
  const pricing = read("src/components/dreelio/pricing-data.ts");
  const tiers = pricing.slice(pricing.indexOf("export const PRICING_TIERS"), pricing.indexOf("type ComparisonValue"));
  assert.equal((tiers.match(/id:\s*"(?:free|plus)"/g) ?? []).length, 2);
});

test("legacy Family records are safely migrated to Plus", () => {
  const migrationName = readdirSync(file("supabase/migrations"), { withFileTypes: true })
    .find((entry) => entry.isFile() && entry.name.endsWith("_remove_family_plan.sql"))?.name;
  assert.ok(migrationName, "remove_family_plan migration must be generated by the Supabase CLI");
  const migrationPath = `supabase/migrations/${migrationName}`;
  assert.equal(existsSync(file(migrationPath)), true);
  const migration = read(migrationPath);

  assert.match(migration, /update\s+public\.app_members[\s\S]*set\s+plan\s*=\s*'plus'[\s\S]*where\s+plan\s*=\s*'family'/i);
  assert.match(migration, /update\s+public\.subscriptions[\s\S]*set\s+plan\s*=\s*'plus'[\s\S]*where\s+plan\s*=\s*'family'/i);
  assert.match(migration, /check\s*\(plan\s+in\s*\('free',\s*'plus'\)\)/i);
  assert.match(migration, /check\s*\(plan\s*=\s*'plus'\)/i);
});

test("subscription cancellation is scheduled for the billing-period end", () => {
  const razorpay = read("src/lib/server/razorpay.ts");
  const route = read("src/app/api/payments/cancel/route.ts");
  const settings = read("src/components/settings/PlanSettings.tsx");

  assert.match(razorpay, /JSON\.stringify\(\{\s*cancel_at_cycle_end:\s*true\s*\}\)/);
  assert.match(route, /cancel_at_cycle_end:\s*true/);
  assert.match(route, /const \{ error: updateError \}/);
  assert.match(route, /if \(updateError\) throw updateError/);
  assert.doesNotMatch(route, /status:\s*"cancelled"/);
  assert.match(settings, /Cancellation scheduled/);
  assert.match(settings, /cancel_at_cycle_end/);
});
